# Generated by Django 3.0.3 on 2020-02-18 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app04', '0003_book_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='author',
            old_name='date_of_deat',
            new_name='date_of_death',
        ),
    ]
