# Generated by Django 3.0.3 on 2020-04-01 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app04', '0006_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
