# Generated by Django 3.0.3 on 2020-04-27 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app04', '0008_auto_20200426_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_edit_book', 'Create, edit and delete Book'),)},
        ),
    ]
